image:
- Ubuntu1804
services:
- docker
test_script:
- APPVEYOR=True ./run_docker_build.sh
- tar zcvf ffmpeg-static-linux3.tgz build/linux3
- tar zcvf ffmpeg-static-linux2.tgz build/linux2
artifacts:
- path: ffmpeg-static-linux3.tgz
  name: FFmpeg Static Tarball for GNU/Linux 3.2.0 Binary
- path: ffmpeg-static-linux2.tgz
  name: FFmpeg Static Tarball for GNU/Linux 2.6.32 Binary
build: off
