image:
- Ubuntu1804
services:
- docker
environment:
  APPVEYOR: True
  matrix:
  - DEBVER: buster
  - DEBVER: stretch
test_script:
- ./run_docker_build.sh
- tar zcvf ffmpeg-static-linux-$DEBVER.tgz build/$DEBVER/bin/ffmpeg build/$DEBVER/bin/ffprobe

for:

-
  matrix:
    only:
      - DEBVER: buster
  artifacts:
  - path: ffmpeg-static-linux-buster.tgz
    name: FFmpeg Static GNU/Linux 3.2.0 Binary

-
  matrix:
    only:
      - DEBVER: stretch
  artifacts:
  - path: ffmpeg-static-linux-stretch.tgz
    name: FFmpeg Static GNU/Linux 2.6.32 Binary

build: off
