image:
- Ubuntu1804
services:
- docker
environment:
  APPVEYOR: True
  matrix:
  - DEBVER: buster
  - DEBVER: stretch
test_script:
- ./run_docker_build.sh
- tar zcvf ffmpeg-static-linux.tgz build/$DEBVER
artifacts:
- path: ffmpeg-static-linux.tgz
  name: FFmpeg Static Linux Binary
build: off
